core/urls.py
from django import views
from django.urls import path,include
from core.views import category_list_view,index,product_list_view,category_product_list_view,vendor_list_view,vendor_detail_view,product_detail_view,tag_list,ajax_add_review,search_view,filter_product,add_to_cart,cart_view,delete_item_from_cart,update_cart,checkout,payment_completed_view,payment_failed_view,customer_dashboard,order_detail,make_address_default,wishlist_view,add_to_wishlist,remove_wishlist, contact,about_us,purchase_guide,privacy_policy,terms_of_service,ajax_contact_form,blogs
from core import views
app_name = "core"

urlpatterns = [
    path("",index,name="index"),
    path("products/",product_list_view,name="product-list"),
    path("product/<pid>/",product_detail_view,name="product-detail"),
    path("category/",category_list_view,name="category-list"),
    path("category/<cid>/",category_product_list_view,name="category-product-list"),
    path("vendors/",vendor_list_view,name="vendor-list"),
    path("vendors/<vid>/",vendor_detail_view,name="vendor-detail"),
    path("product/tag/<slug:tag_slug>/",tag_list,name="tags"),
    path("ajax-add-review/<pid>",ajax_add_review,name="ajax-add-review"),
    path("search/",search_view,name="search"),
    path("filter-products/",filter_product,name="filter_product"),
    path("add-to-cart/",add_to_cart,name="add_to_cart"),
    path("cart/",cart_view,name="cart"),
    path("delete-from-cart/",delete_item_from_cart,name="delete-from-cart"),
    path("update-cart/",update_cart,name="update-cart"),
    path("checkout/<oid>",checkout,name="checkout"),
    path("paypal/",include('paypal.standard.ipn.urls')),
    path("payment-completed/<oid>/",payment_completed_view,name="payment-completed"),
    path("payment-failed/",payment_failed_view,name="payment-failed"),
    path("dashboard/",customer_dashboard,name="dashboard"),
    path("dashboard/order/<int:id>",order_detail,name="order-detail"),
    path("make_default_address",make_address_default,name="make_default_address"),
    path("wishlist",wishlist_view,name="wishlist"),
    path("add-to-wishlist",add_to_wishlist,name="add-to-wishlist"),
    path("remoce-from-wishlist",remove_wishlist,name="remoce-from-wishlist"),

    #Otras
    path("contact/",contact,name="contact"),
    path("ajax-contact-form/",ajax_contact_form,name="ajax-contact-form"),
    path("about_us/",about_us,name="about_us"),
    path("purchase_guide/",purchase_guide,name="purchase_guide"),
    path("privacy_policy/",privacy_policy,name="privacy_policy"),
    path("terms_of_service/",terms_of_service,name="terms_of_service"),
    path("save_checkout_info/",views.save_checkout_info,name="save_checkout_info"),
    path("api/cerate_checkout_session/<oid>",views.create_checkout_session,name="cerate_checkout_session"),
    path("blogs/",blogs,name="blogs"),
    path("blog_content/<id>",views.blog_content,name="blog_content"),



    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("user/",include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),
    #path("ckeditor/",include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    

]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    

useradmin/urls.py
from django.urls import path
from useradmin import views

app_name = "useradmin"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("products/", views.products, name="products"),
    path("add_product/", views.add_product, name="add_product"),
    path("edit_product/<pid>/", views.edit_product, name="edit_product"),
    path("delete_product/<pid>/", views.delete_product, name="delete_product"),

    path("orders/", views.orders, name="orders"),
    path("order_detail/<id>/", views.order_detail, name="order_detail"),
    path("change_order_status/<oid>/", views.change_order_status, name="change_order_status"),
    path("change_order_status/<oid>/", views.change_order_status, name="change_order_status"),
    path("shop_page/", views.shop_page, name="shop_page"),
    path("reviews/", views.reviews, name="reviews"),
    path("settings/", views.settings, name="settings"),
    path("change_password/", views.change_password, name="change_password"),
    


]

userauths/urls.py
from django.urls import path
from userauths import views
app_name = "userauths"

urlpatterns = [
    path("sign-up/",views.register_view,name="sign-up"),
    path("sign-in/",views.login_view,name="sign-in"),
    path("sign-out/",views.logout_view,name="sign-out"),
    path("profile/update/",views.profile_update,name="profile-update")

]


core/models.py
from email.policy import default
from pyexpat import model
from unicodedata import decimal
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from userauths.models import User
from taggit.managers import TaggableManager
from django_ckeditor_5.fields import CKEditor5Field
#from ckeditor_uploader.fields import RichTextUploadingField
STATUS_CHOICE = (
    ("processing","En Proceso"),
    ("shipped","Enviado"),
    ("delivered","Entregado")
)

STATUS = (
    ("draft","Borrador"),
    ("disabled","Desactivado"),
    ("rejected","Rechazado"),
    ("in_review","En Revision"),
    ("published","Publicado"),
)


RATING = (
    ("1","⭐✧✧✧✧"),
    ("2","⭐⭐✧✧✧"),
    ("3","⭐⭐⭐✧✧"),
    ("4","⭐⭐⭐⭐✧"),
    ("5","⭐⭐⭐⭐⭐"),
)
def user_directory_path(instance,filename):
    return 'user{0}/{1}'.format(instance.user.id,filename)
class Category(models.Model):
    cid = ShortUUIDField(unique=True,prefix="cat",alphabet="abcdefgf12345")
    
    title = models.CharField(max_length=254,default='Categoria' )
    image = models.ImageField(upload_to="category",default='category.jpg')
    description = models.TextField(null=True,blank=True,default='Categoria')
    category_status = models.BooleanField(null=False,default=False)

    class Meta:
        verbose_name_plural="Categorias"
    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' % (self.image.url))
    def __str__(self):
        return self.title
class Tags(models.Model):
    pass
class Vendor(models.Model):
    vid = ShortUUIDField(unique=True,prefix="ven",alphabet="abcdefgf12345")
    
    title = models.CharField(max_length=254,default='Vendedor' )
    image = models.ImageField(upload_to=user_directory_path,default='vendor.jpg')
    cover_image = models.ImageField(upload_to=user_directory_path,default='vendor.jpg')
    description = CKEditor5Field(config_name='extends',null=True,blank=True,default='Descripcion')

    address = models.CharField(max_length=255,null=True,blank=True)
    contact = models.CharField(max_length=255,null=True,blank=True)
    chat_resp_time = models.CharField(max_length=255,default="100")
    shipping_on_time =models.CharField(max_length=255,default="100")
    autentic_rating =models.CharField(max_length=255,default="100")
    days_return =models.CharField(max_length=255,default="100")
    warranty_period = models.CharField(max_length=255,default="100")
    user = models.ForeignKey(User,on_delete=models.RESTRICT,null=False)
    date = models.DateTimeField(auto_now_add=True,null=True,blank=True)

    class Meta:
        verbose_name_plural="Vendedores"
    def vendor_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' % (self.image.url))
    def __str__(self):
        return self.title

class Product(models.Model):
    pid = ShortUUIDField(unique=True,prefix="prod",alphabet="abcdefgf12345")
    user = models.ForeignKey(User,on_delete=models.RESTRICT,null=False)
    category = models.ForeignKey(Category,on_delete=models.RESTRICT,null=False,related_name="category")
    vendor = models.ForeignKey(Vendor,on_delete=models.RESTRICT,null=False,default="0",related_name="product")

    title = models.CharField(max_length=254,default='Este es un Producto')
    image = models.ImageField(upload_to=user_directory_path,default='product.jpg')
    description = CKEditor5Field(config_name='extends', null=True, blank=True)
    price = models.DecimalField(max_digits= 12,decimal_places=2,default="0.00")
    old_price = models.DecimalField(max_digits= 12,decimal_places=2,default="0.00")
    specifications = CKEditor5Field(config_name='extends', null=True, blank=True)
    type = models.CharField(max_length=100,default="Type",null=True,blank=True)
    stock_count = models.CharField(max_length=100,default="0",null=True,blank=True)
    life = models.CharField(max_length=100,default="100 dias",null=True,blank=True)
    mfd = models.DateTimeField(auto_now_add=False,null=True,blank=True)
    tags = TaggableManager(blank=True)
    #tags = models.ForeignKey(Tags,on_delete=models.RESTRICT,null=False)
    product_status = models.CharField(choices=STATUS,max_length=10,default='in_review')
    status = models.BooleanField(default=True)
    in_sock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    digital = models.BooleanField(default=False)
    sku = ShortUUIDField(unique=True,prefix="sku",alphabet="12345678900")
    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True,blank=True)

    class Meta:
        verbose_name_plural="Productos"
    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' % (self.image.url))
    def __str__(self):
        return self.title
    def get_precentage(self):
        if(self.old_price>0):
            new_price = round((self.price / self.old_price)*100,0)
        else:
            new_price=0
        return new_price
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images",default="product.jpg")
    product = models.ForeignKey(Product,related_name="p_images", on_delete=models.RESTRICT)
    date = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural="Imaganes de Productos"
class CartOrder(models.Model):
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    full_name = models.CharField(max_length=255,null=True,blank=True)
    email = models.CharField(max_length=255,null=True,blank=True)
    phone = models.CharField(max_length=255,null=True,blank=True)
    address = models.CharField(max_length=255,null=True,blank=True)
    city = models.CharField(max_length=255,null=True,blank=True)
    state = models.CharField(max_length=255,null=True,blank=True)
    country = models.CharField(max_length=255,null=True,blank=True)
    price = models.DecimalField(max_digits= 12,  decimal_places=2,default="0.00")
    saved = models.DecimalField(max_digits= 12,  decimal_places=2,default="0.00")
    coupons = models.ManyToManyField("core.Coupon",blank=True)
    shipping_method = models.CharField(max_length=255,null=True,blank=True)
    tracking_id = models.CharField(max_length=255,null=True,blank=True)
    tracking_website_address = models.CharField(max_length=255,null=True,blank=True)
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices=STATUS_CHOICE,default="Procesando",blank=True,null=True)
    sku = ShortUUIDField(null=True,blank=True,length=5,prefix="SKU",max_length=20,alphabet="1234567890")
    oid = ShortUUIDField(null=True,blank=True,length=5,max_length=20,alphabet="1234567890")
    stripe_payment_intent = models.CharField(max_length=100,null=True,blank=True)
    class Meta:
        verbose_name_plural="Carrito"
class CartOrderProducts(models.Model):
    order = models.ForeignKey(CartOrder,on_delete=models.RESTRICT)
    invoice_no = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    qty = models.IntegerField(default=0)
    price = models.DecimalField(max_digits= 12,decimal_places=2,default=0)
    total = models.DecimalField(max_digits= 12,decimal_places=2,default=0)
    class Meta:
        verbose_name_plural="Carrito Detalle"
    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' % (self.image.url))
    def order_img(self):
        return mark_safe('<img src="media/%s" width="50" height="50"/>' % (self.image))
class ProductReview(models.Model):
    user = models.ForeignKey(User,on_delete=models.RESTRICT,null=False)
    product = models.ForeignKey(Product,on_delete=models.RESTRICT,null=False,related_name="reviews")
    review = models.TextField()
    rating = models.IntegerField(choices=RATING,default=None)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural="Revisiones de Productos"
    
    def __str__(self):
        return self.title
    def get_rating(self):
        return self.rating
class wishlist_model(models.Model):
    user = models.ForeignKey(User,on_delete=models.RESTRICT,null=False)
    product = models.ForeignKey(Product,on_delete=models.RESTRICT,null=False)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural="Lista de deseos"
class Address(models.Model):
    user = models.ForeignKey(User,on_delete=models.RESTRICT,null=False)
    mobile = models.CharField(max_length=255,null=True,blank=True)
    address = models.CharField(max_length=255,null=True,blank=True)
    status = models.BooleanField(default=False)
    class Meta:
        verbose_name_plural="Direcciones"
class Coupon(models.Model):
    code =models.CharField(max_length=50)
    discount = models.IntegerField(default=0)
    active=models.BooleanField(default=True)
    def __str__(self):
        return self.code
class Blog(models.Model):
    fecha = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255,default="titulo")
    contenido =CKEditor5Field(config_name='extends', null=True, blank=True)
    status = models.BooleanField(default=True)
    image = models.ImageField(upload_to="blogs",default='default.jpg')
    
    class Meta:
        verbose_name_plural="Blogs"
    def __str__(self):
        return self.contenido

useradmin/models.py
from django.db import models

# Create your models here.

useradmin/forms.py
from core.models import Product
from django import forms
# from bootstrap_datepicker_plus import DatePickerInput



class AddProductForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Product Title", "class":"form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Product Description", "class":"form-control"}))
    price = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "Sale Price", "class":"form-control"}))
    old_price = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "Old Price", "class":"form-control"}))
    type = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Type of product e.g organic cream", "class":"form-control"}))
    stock_count = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "How many are in stock?", "class":"form-control"}))
    life = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "How long would this product live?", "class":"form-control"}))
    mfd = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'placeholder': "e.g: 22-11-02", "class":"form-control"}))
    tags = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Tags", "class":"form-control"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={"class":"form-control"}))

    class Meta:
        model = Product
        fields = [
            'title',
            'image',
            'description',
            'price',
            'old_price',
            'specifications',
            'type',
            'stock_count',
            'life',
            'mfd',
            'tags',
            'digital',
            'category',
        ]

        widgets = {
        # 'mdf': DateTimePickerInput
    }

templates/useradmin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>E-commerce Dashboard</title>
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="" />
        <meta property="og:type" content="" />
        <meta property="og:url" content="" />
        <meta property="og:image" content="" />
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="assets2/imgs/theme/favicon.svg" />
        <!-- Template CSS -->
        <link href="{% static 'assets2/css/main.css' %}" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />

    </head>

    <body>
        <div class="screen-overlay"></div>
        <aside class="navbar-aside" id="offcanvas_aside">
            <div class="aside-top">
                <a href="/useradmin/" class="brand-wrap">
                    <img src="https://clipground.com/images/ecommerce-logo-png-11.png" class="logo" alt="E-commerce Dashboard" />
                </a>
                <div>
                    <button class="btn btn-icon btn-aside-minimize"><i class="text-muted material-icons md-menu_open"></i></button>
                </div>
            </div>
            <nav>
                <ul class="menu-aside">
                    <li class="menu-item {% if '/useradmin/dashboard/' in request.path %}active{% endif %}">
                        <a class="menu-link" href="/useradmin/">
                            <i class="icon material-icons md-home"></i>
                            <span class="text">Dashboard</span>
                        </a>
                    </li>
                    <li class="menu-item {% if '/useradmin/products/' in request.path %}active{% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:products' %}">
                            <i class="icon material-icons md-shopping_bag"></i>

                            <span class="text">Products</span>
                        </a>
                    </li>
                    <li class="menu-item {% if '/useradmin/orders/' in request.path %}active{% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:orders' %}">
                            <i class="icon material-icons md-shopping_cart"></i>
                            <span class="text">Orders</span>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'useradmin:shop_page' %}">
                            <i class="icon material-icons md-store"></i>
                            <span class="text">Shop Page</span>
                        </a>
                    </li>
                    <li class="menu-item ">
                        <a class="menu-link" href="{% url 'useradmin:add_product' %}">
                            <i class="icon material-icons md-add_box"></i>
                            <span class="text">Add product</span>
                        </a>
                    </li>

                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'useradmin:reviews' %}">
                            <i class="icon material-icons md-comment"></i>
                            <span class="text">Reviews</span>
                        </a>
                    </li>
                </ul>
                <hr />
                <ul class="menu-aside">
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'useradmin:settings' %}">
                            <i class="icon material-icons md-settings"></i>
                            <span class="text">Settings</span>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'useradmin:change_password' %}">
                            <i class="icon material-icons md-lock"></i>
                            <span class="text"> Change Password </span>
                        </a>
                    </li>

                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'userauths:sign-out' %}">
                            <i class="icon material-icons md-arrow_forward"></i>
                            <span class="text">Logout</span>
                        </a>
                    </li>
                </ul>
                <br />
                <br />
            </nav>
        </aside>
        <main class="main-wrap">
            <header class="main-header navbar">
                <div class="col-search">
                    
                </div>
                <div class="col-nav">
                    <button class="btn btn-icon btn-mobile me-auto" data-trigger="#offcanvas_aside"><i class="material-icons md-apps"></i></button>
                    <ul class="nav">
                       
                        <li class="nav-item">
                            <a href="#" class="requestfullscreen nav-link btn-icon"><i class="material-icons md-cast"></i></a>
                        </li>
                        
                        <li class="dropdown nav-item">
                            <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownAccount" aria-expanded="false"> 
                                
                                {% if request.user.profile.image %}
                                <img class="img-xs rounded-circle" src="{{request.user.profile.image.url}}" alt="User" />
                                {% else %}
                                <img class="img-xs rounded-circle" src="https://www.shutterstock.com/image-vector/vector-flat-illustration-grayscale-avatar-600nw-2281862025.jpg" alt="User" />

                                {% endif %}
                                    
                            </a>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownAccount">
                                <a class="dropdown-item" href="#"><i class="material-icons md-perm_identity"></i>Edit Profile</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-settings"></i>Account Settings</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-account_balance_wallet"></i>Wallet</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-receipt"></i>Billing</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-help_outline"></i>Help center</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item text-danger" href="#"><i class="material-icons md-exit_to_app"></i>Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </header>

            {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}">
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <script>
                    setTimeout (() => {
                        $(".alert").alert("close");
                    }, 3000)
                </script>

            {% block content %} 
            
            {% endblock content %}

            <!-- content-main end// -->
            <footer class="main-footer font-xs">
                <div class="row pb-30 pt-15">
                    <div class="col-sm-6">
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                        &copy; E-commerce - HTML Ecommerce Template .
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end">All rights reserved</div>
                    </div>
                </div>
            </footer>
        </main>
        <script src="{% static 'assets2/js/vendors/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/select2.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/perfect-scrollbar.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/jquery.fullscreen.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/chart.js' %}"></script>
        <!-- Main Script -->
        <script src="{% static 'assets2/js/main.js?v=1.1' %}" type="text/javascript"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <!-- <script src="{% static 'assets2/js/custom-chart.js' %}" type="text/javascript"></script> -->
    </body>
</html>

templates/useradmin/products.html
{% extends 'useradmin/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Products List</h2>
            <p>Manage all your products from here</p>
        </div>
        <div>
            <a href="{% url 'useradmin:add_product' %}" class="btn btn-primary btn-sm rounded">Create Product</a>
        </div>
    </div>
    <div class="card mb-4">
        <header class="card-header">
            <div class="row align-items-center">
                
                <div class="col-md-2 col-6">
                    <select class="form-select">
                        <option selected>Status</option>
                        <option>Active</option>
                        <option>Disabled</option>
                        <option>Show all</option>
                    </select>
                </div>
            </div>
        </header>
        <div class="card-body">
            {% for p in all_products %}
            <article class="itemlist">
                <div class="row align-items-center">
                    <div class="col-lg-4 col-sm-4 col-8 flex-grow-1 col-name">
                        <a class="itemside" href="{% url 'core:product-detail' p.pid %}">
                            <div class="left">
                                <img src="{{p.image.url}}" style="width: 100px; height: 100px; object-fit: cover; border-radius: 15px;" class="img-sm img-thumbnail" alt="Item" />
                            </div>
                            <div class="info">
                                <h6 class="mb-0">{{p.title}}</h6>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-2 col-sm-2 col-4 col-price"><span>${{p.price}}</span></div>
                    <div class="col-lg-2 col-sm-2 col-4 col-status"><span class="badge  alert-dark">{{p.product_status|title}}</span></div>
                    <div class="col-lg-1 col-sm-2 col-4 col-date"><span>{{p.date}}</span></div>
                    <div class="col-lg-2 col-sm-2 col-4 col-action text-end">
                        <a href="{% url 'useradmin:edit_product'  p.pid %}" class="btn btn-sm font-sm rounded btn-brand"> <i class="material-icons md-edit"></i> Edit </a>
                        <a href="{% url 'useradmin:delete_product' p.pid  %}" class="btn btn-sm font-sm btn-light rounded"> <i class="material-icons md-delete_forever"></i> Delete </a>
                    </div>
                </div>
            </article>
            {% endfor %}
        </div>
    </div>
    
</section>

{% endblock content %}

templates/useradmin/reviews.html
{% extends 'useradmin/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}    

<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Reviews</h2>
            <p>Manage all product reviews</p>
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>S/N</th>
                            <th>Product</th>
                            <th>Name</th>
                            <th>Review</th>
                            <th>Rating</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        {% for r in reviews %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td><b>{{r.product.title}}</b></td>
                                <td>{{r.user.username|title}}</td>
                                <td>{{r.review}}</td>
                                <td>{{r.rating}} Stars</td>
                                <td>{{r.date|date:"m M, Y"}}</td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock content %}    